### ISSUE TITLE
Use an UUID to identify a Node or an Edge

### ISSUE THREAD

**Issue by hmarchadour** [eclipse-sirius/sirius-components#156]
* [x] **I have checked that this feature has not yet been suggested by someone else.**

### Expected behavior
According to the following PR feedback
https://github.com/eclipse-sirius/sirius-components/pull/140#discussion_r533488100

We should identify nodes and edges with an UUID (and use an UUID in the graphQL API).

The NodeMappingConverter, the idProvider give a string ```UUID.randomUUID().toString()``` -> we can remove the toString...
The EdgeMappingConverter, the idProvider give a string ```sourceId + " --> " + targetId + " - " + count``` -> we could transform this string in a UUID ```UUID.nameUUIDFromBytes```.

This implies :
* update graphQL API
  * Use @GraphQLID annotation for nodeIds/edgeIds in IDiagramInput implementations
* use UUID for
  * Node#id
  * NodeDescription#idProvider
  * NodeElementProps
  * Edge#id
  * EdgeDescription#idProvider
  * EdgeElementProps
  * IDiagramService#findNodeById
  * IDiagramService#findEdgeById

We should replace the idProvider type from Function<VariableManager, String> to Function<VariableManager, UUID>.

### Cuttings backs

We should probably do the same job with Label/ToolSection/ITool.
The Label id has a suffix pattern that we should review but it makes sens to cut this work in another issue. (To open before close this issue...) @see EdgeMappingConverter.convert and LabelDescription.LABEL_SUFFIX.

### Potential side effects

* Diagram refresh
* invoke tool / delete

**Comment by pcdavid** [comment]
> The NodeMappingConverter, the idProvider give a string `UUID.randomUUID().toString()` -> we can remove the toString...
> The EdgeMappingConverter, the idProvider give a string `sourceId + " --> " + targetId + " - " + count` -> we could transform this string in a UUID `UUID.nameUUIDFromBytes`.

For the edges, this is similar to the approach taken in https://github.com/eclipse-sirius/sirius-components/pull/139, which builds a discriminant by concatenating (in a string) all the ids / parameters which uniquely identify an element and then builds the final id using `UUID.nameUUIDFromBytes`.

Indeed, in my patch linked above I had not modified the `idProvider` for edges, because the existing logic guarantees it will be stable as long as the `sourceId` and `targetId` are (which the patch ensures). Well, except for the iteration order which determines the `count`. Maybe this part of the edge id discriminant should be replaced with the id of the edge description? The triplet `sourceId`, `targetId` and `descriptionId` should be both unique and stable, and this would unify the handling of all ids.

**Comment by sbegaudeau** [comment]
This has been merged in master but @pcdavid's comment regarding future improvements on the generation of the edge id are still valid. We should keep that in mind.
