### ISSUE TITLE
Get the documentId in sirius-web

### ISSUE THREAD

**Issue by 4MIR2000** [eclipse-sirius/sirius-components#1802]
Hi everyone,
is it possible to get the documentId of  the current representation through a graphql request?
Or can I access it somehow in the "DiagramWebSocketContainer.tsx" of the frontend?

**Comment by pcdavid** [comment]
`DiagramWebSocketContainer` (now called `DiagramRepresentation`) manages a single diagram at a time, and there is no specific `documentId` associated to a given diagram.

Representations (incl. diagram) are not Documents, and not stored *in* Documents. They appear inside the structure of a Document in the explorer because they are "attached" to a specific semantic element, which itself belongs to a document, but that's all.
