### ISSUE TITLE
Add support for Size Computation Expression for edges

### ISSUE THREAD

**Issue by mt-empty** [eclipse-sirius/sirius-components#407]
* [x] **I have checked that this feature has not yet been suggested by someone else.**

### Expected behavior

`Size Computation Expression` is currently ignored and every edge has a size of `1`.
![image](https://user-images.githubusercontent.com/59728838/112317513-3eea7000-8d00-11eb-9d4a-8d0682e62ff5.png)

### Cuttings backs

...

### Potential side effects

...

### Describe alternatives you've considered

Editing the CSS.

**Comment by pcdavid** [comment]
PR #409 seems to work, but still needs some automated tests before it can be merged. 

With a simple `sizeComputationExpression="aql:self.name.size()"` on a reference-based edge I get:

![2021-03-24_17-06](https://user-images.githubusercontent.com/10608/112344082-0a58c300-8cc4-11eb-8330-7868e08aeb3c.png)

**Comment by mt-empty** [comment]
Just to be clear, I was referring to Sirius web edges. `stroke-width` doesn't map `sizeComputationExpression`
![image](https://user-images.githubusercontent.com/59728838/112471415-fd20fe80-8dbf-11eb-9073-820a5a58bd62.png)

**Comment by pcdavid** [comment]
I undestand, the screenshot in my previous comment is from a Sirius Web modeler. Here the `stroke-width` is `6` because that is the length of `"Engine"`, i.e. the result of `aql:self.name.size()`.

![2021-03-25_13-48](https://user-images.githubusercontent.com/10608/112475143-c7a0f480-8d70-11eb-9665-678e66a38777.png)
