### ISSUE TITLE
Improve the View and Domain DSLs

### ISSUE THREAD

**Issue by sbegaudeau** [eclipse-sirius/sirius-components#561]
### Problem

The first version of the View and Domain DSLs has been introduced but it still has some rough edges. This issue will be used to consider some improvements to those two new DSLs.

### Solution

The list of issues really considered and done for the 0.4.0 can be found using both of those links:

- [Domain related issues](https://github.com/eclipse-sirius/sirius-components/issues?q=is%3Aissue+label%3A%22area%3A+domain%22+project%3Aeclipse-sirius%2Fsirius-components%2F2+)
- [View related issues](https://github.com/eclipse-sirius/sirius-components/issues?q=is%3Aissue+label%3A%22area%3A+view%22+project%3Aeclipse-sirius%2Fsirius-components%2F2+)

The list of existing issues not considered for the 0.4.0 can be found using those links:

- [Domain related issues open](https://github.com/eclipse-sirius/sirius-components/issues?q=is%3Aissue+label%3A%22area%3A+domain%22+is%3Aopen+)
- [View related issues open](https://github.com/eclipse-sirius/sirius-components/issues?q=is%3Aissue+label%3A%22area%3A+view%22+is%3Aopen)

### Test

* [ ] Automated developer tests merged and pass (with reasonable code coverage)
* [ ] Automated End-to-End tests  merged and pass (Cypress)
* [ ] Feature/bug fix manually tested/validated by at least one person not involved in the implementation
* [ ] Collaborative tests passed by hand
* [ ] Exploratory test passed by MEB
* [ ] Business acceptance test passed by MEB

### Doc
* [ ] Internal Doc updated
* [ ] External Doc updated
* [ ] Validation Doc updated

### UX/UI
* [ ] Zeroheight updated
* [ ] Storybook updated

### Next
* [ ] Any left-over tasks added to the issues on Github

**Comment by pcdavid** [comment]
Additional features, more in the scope of "EMF Edit" but that could be useful to define directly as part of the Domain:

* Set a custom icon for entities/types (and make sure it is used when displaying instances).
* Maybe set an expression to compute the default label.
* Other EMF Edit features?

**Comment by pcdavid** [comment]
Not directly related to this, but from what I've seen it seems EMF JSON is not as resilient as EMF's XMI serialization when it comes to some "innocent" changes on the metamodel side. For exemple if I have serialized a model using v1 of a domain definition where some reference is single-valued (serialized as a direct object JSON) and then try to load the same document using an updated v2 of the metamodel where the reference is now multi-valued (serialized as an array of objects), EMF JSON crashes (deep in Gson) with a "not an array" message.

I'd have to test again to confirm, and see if there are other similar issues that could be fixed in EMF JSON directly to make the system more resilient to small changes like this.

**Comment by pcdavid** [comment]
It should not be possible to have a domain with an URI which can conflict with an nsURI from the "static" metamodel (in particular with EMF and the Sirius Desktop metamodels).

* At the very least, `DomainConverter` should refuse to convert/publish domains whose URI starts with `http`.
* Better: only consider domains whose URI starts with `domain://`
* Best: if the `domain://` prefix is mandatory, do not ask for it at all.

**Comment by sbegaudeau** [comment]
Closing this issue since the work for the 0.4.0 is now completed.
