### ISSUE TITLE
Improve studio definition

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-components#737]
This is a "meta-issue" to keep track of the fixes and improvements of the studio definition feature in v0.5.0

- [x] https://github.com/eclipse-sirius/sirius-components/issues/735
- [ ] [The "relation" edge creation tool in the domain modeler does not use the correct icon](https://github.com/eclipse-sirius/sirius-components/pull/730/commits/892a7a6b53aebaa5fffdad9298a456759f6a713e)
- [ ] [The supertype edge creation tool in the domain modeler is broken since we added support for multiple inheritance](https://github.com/eclipse-sirius/sirius-components/pull/730/commits/ccf2a2019b33fcd8cfbfda76cafeeb00cef93115)
  - the name of the relation to edit was not updated
- [ ] https://github.com/eclipse-sirius/sirius-components/issues/727
- [ ] https://github.com/eclipse-sirius/sirius-components/issues/741
- [ ] https://github.com/eclipse-sirius/sirius-components/issues/731
- [ ] https://github.com/eclipse-sirius/sirius-components/issues/743
- [ ] https://github.com/eclipse-sirius/sirius-components/issues/738
- [ ] https://github.com/eclipse-sirius/sirius-components/issues/739
- [ ] https://github.com/eclipse-sirius/sirius-components/issues/726
- [ ] https://github.com/eclipse-sirius/sirius-components/issues/740

**Comment by sbegaudeau** [comment]
What is the point of such "meta-issues"? It will never represent what is really being done in the 0.5.0 release since it will require manual update contrary to what's in the milestone. Some of those issues are not in the milestones (and some will never be in it), others are in the milestones and have been done already but do not appear here.

The real up-to-date answer is [there](https://github.com/eclipse-sirius/sirius-components/issues?q=milestone%3A0.5.0+label%3A%22area%3A+domain%22%2C%22area%3A+view%22) isn't it? Feel free to reopen it if I'm missing something but I've added the `area: domain` and `area: view` labels especially because our previous attempts at manually following this kind of things failed.
