### ISSUE TITLE
Add support for multilines labels

### ISSUE THREAD

**Issue by Gelio** [eclipse-sirius/sirius-components#781]
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- other: 0.4.6
* [x] **I have specified my environment** : 
- Ubuntu 20.04 LTS

### Screenshots

Sirius Desktop
![image](https://user-images.githubusercontent.com/889383/137633043-14826c84-e44b-434a-99e0-1d727d317d2b.png)

Sirius Web (a long single line label)
![image](https://user-images.githubusercontent.com/889383/137633050-5103a1d3-1d85-4cbd-b61c-cbdaaba47635.png)

### Steps to reproduce

In the _Label Expression_ for a node, add a newline

![image](https://user-images.githubusercontent.com/889383/137633071-1a78db44-dfd7-46f1-9645-063c96449a25.png)

### Expected behavior

The newline makes the rest  of the text appear on a new line

### Actual behavior

The text appears on a single line. The newline is turned into a space.

**Comment by lfasani** [comment]
## Specification
### Model
The model owns somewhere an entity with an attribute of type string. There is currently not the information about if the string is mono or multiline.
So let's consider that or line return is serialized with `\n`
The end-user '\n' string will be serialized escaped with '\\n'

### Representation
Every representation of a string attribute should manage the mono or multiline information based on th `\n` character

### Form representation
By default, the form representation represents a string with a textField. But a string could also be represented by a textArea

The textField will display `\n` with `\n` and `\\n` with `\\n`

The textArea will display `\n` with a carriage return and `\\n` with `\n`

### Sprotty

The label will display `\n` with a carriage return and `\\n` with `\n`
Idem when editing the text

### backend layout
The ELK and incremental layout should adapt to mange the fact the a label can be displayed on many lines.
The is necessary so that the parent node have the right size and so that the children nodes will not overlap the parent node label
