### ISSUE TITLE
CreateView depending on others CreateView are not supported

### ISSUE THREAD

**Issue by AxelRICHARD** [eclipse-sirius/sirius-components#840]
* [x] **I have checked that this feature has not yet been suggested by someone else.**

### Expected behavior

CreateView have a "variable name" attribute. If you want to define a CreateView depending on another CreateView (in https://github.com/ObeoNetwork/Flow-Designer/blob/ocp/plugins/fr.obeo.dsl.designer.sample.flow.design/description/flow.odesign#L979 fro example), you cannot do it because the "variable name" defined in the first CreateView is not supported in the sirius-web-emf project (see org.eclipse.sirius.web.emf.compatibility.modeloperations.CreateViewOperationHandler#handle method).
The problem seems have deep impacts because the CreateView operations are all executed on diagram refresh and not in the CreateViewOperationHandler#handle method.

**Comment by sbegaudeau** [comment]
I am not 100% sure that I understand the issue but the refresh strategy of Sirius Components' diagrams is indeed very different from Sirius Desktop's ones. From what I understand, we would need a way to dynamically compute `ViewCreationRequest` in the refresh and let the compatibility layer provide how.

I don't think that it's that difficult to make but it would require a very precise ADR in order to find out how.
