### ISSUE TITLE
Default object images from model.edit/icons/full/obj16 are not used

### ISSUE THREAD

**Issue by Gelio** [eclipse-sirius/sirius-components#866]
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- other: 0.5.3
* [x] **I have specified my environment** : 
- Ubuntu 20.04 LTS

### Screenshots

Sirius Desktop automatically generated icons for each object in the metamodel. They are in the `.edit` package, in the `icons/full/obj16` directory. I have modified those icons. They are correctly shown in the model tree in Sirius Desktop:

![image](https://user-images.githubusercontent.com/889383/144720330-82ccef40-14fb-41f6-8dea-4d20088f70f1.png)

When using that model in Sirius Web, it still loads the same default icons:

![image](https://user-images.githubusercontent.com/889383/144720358-27e68e7a-5fa4-43b1-906c-c6e981f5b9c1.png)

The URLs for those images returned in the `treeEvent` subscription are:

```
/api/images/icons/full/obj16/Item.gif#UnitCall
```

whereas they should be:

```
/api/images/icons/full/obj16/UnitCall.gif
```

as is also defined in the corresponding `*ItemProvider` class in the `.edit` package:

https://github.com/Gelio/CAL-web/blob/a8fc6c6860e810948ab42d354255149229a5bc81/backend/model/eu.balticlsc.model.CAL.edit/src-gen/eu/balticlsc/model/CAL/provider/UnitCallItemProvider.java#L168

### Steps to reproduce

1. Change the default icons generated for metamodel objects

### Expected behavior

Those new icons are used in Sirius Web.

### Actual behavior

The same old icon is used for objects in Sirius Web. The new images are not used. The URL contains the object name as a hash instead of the gif file name.

**Comment by pcdavid** [comment]
Looking at

https://github.com/Gelio/CAL-web/blob/a8fc6c6860e810948ab42d354255149229a5bc81/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/configuration/SampleEMFConfiguration.java#L56-L59

it seems you registered the "basic" `CALAdapterFactory` in the application configuration, instead of the [`CALItemProviderAdapterFactory`](https://github.com/Gelio/CAL-web/blob/a8fc6c6860e810948ab42d354255149229a5bc81/backend/model/eu.balticlsc.model.CAL.edit/src-gen/eu/balticlsc/model/CAL/provider/CALItemProviderAdapterFactory.java) from your `.edit` project.

**Comment by Gelio** [comment]
My bad! I can see the icons correctly after following your suggestion:

![image](https://user-images.githubusercontent.com/889383/144761608-12b8ee40-4b7d-4702-b180-b477b5a4c822.png)

Thanks!
