### ISSUE TITLE
Compatibility layer: handle DotDescription style for Bordered Nodes

### ISSUE THREAD

**Issue by AxelRICHARD** [eclipse-sirius/sirius-components#897]
* [x] **I have checked that this feature has not yet been suggested by someone else.**

### Expected behavior

Handle Dot style for Bordered Nodes in the compatibility layer.
A Dot is simply a RectangularNodeStyle with a radius = 100. 

### Describe alternatives you've considered

A new CircleNodeStyle could be implemented instead of using RectangularNodeStyle with a radius = 100

**Comment by pcdavid** [comment]
I don't understand how we can says that this implements the `DotDescription` from Sirius Desktop, which are represented using a circle. The changelog should a least mention what "handled" means here.

**Comment by sbegaudeau** [comment]
A SVG rectangle with a 100 radius is a circle. No change require on the frontend this way.

**Comment by pcdavid** [comment]
But the border radius is an absolute dimension, not a percentage. It will only render as a Sirius Desktop "Dot" at small sizes:

![2021-12-30_10-22](https://user-images.githubusercontent.com/10608/147738688-572b8949-e243-4f18-bba4-14d742cde399.png)
 
Yes, in SVG the `rx` attribute [*can* be a percentage](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/rx#rect), but in our case `RectangularNodeStyle.getBorderRadius()` is an `int` which we always convert as a plain length.

I guess we could embrace the fact that we will render as SVGs, make `RectangularNodeStyle.getBorderRadius()` a string and return `"100%"` in this case. Which would offer more flexibility to programatically defined modelers to chose between absolute lengths and percentage. Or add a "hack" to interpret negative values as percentage in `RectangleView.tsx` and return `-100` here.

**Comment by sbegaudeau** [comment]
You're right, I believed that we were interpreting it as a percentage on the frontend. We could indeed make `RectangularNodeStyle.getBorderRadius()` a string. We could even create different border radius configurations for each corner. Using that philosophy, I'm not sure why we would not remove both `RectangularNodeStyle.getBorderSize()` and `RectangularNodeStyle.getBorderRadius()` in favor of a string based `RectangularNodeStyle.getBorder()` since it would allow us to create way more complex borders.

**Comment by pcdavid** [comment]
:+1: to "embrace SVG and CSS" (and not try to hide/abstract their more powerful features)
